FROM grafana/grafana:7.1.1

RUN grafana-cli plugins install petrslavotinek-carpetplot-panel && \
    grafana-cli plugins install grafana-googlesheets-datasource && \
    grafana-cli plugins install simpod-json-datasource && \
    grafana-cli \
      --pluginUrl https://github.com/panodata/grafana-map-panel/archive/3f77d553d6a64cff443f5ff8ce391dcdec5cec84.zip \
      plugins install grafana-worldmap-panel-ng
