#!/usr/bin/env bash

# Packages and uploads the app for elasticbeanstalk deployment
#
# Expected environment variables (or circleci equivalents)
#   Provided by caller
#     - AWS_DEFAULT_REGION
#     - S3_BUCKET_NAME
#     - EB_APP_NAME
#
#   Provided by CI
#     - BRANCH_NAME
#     - BUILD_NUMBER
#
# Usage: .elasticbeanstalk/package.sh APP
# Ex: .elasticbeanstalk/package.sh ${SEMAPHORE_PROJECT_NAME}

set -euxo pipefail



BRANCH_NAME="${CIRCLE_BRANCH:-${GITHUB_REF:-${BRANCH_NAME}}}"
BUILD_NUMBER="${CIRCLE_BUILD_NUM:-${GITHUB_RUN_NUMBER:-${BUILD_NUMBER}}}"
DESCRIPTION="${CIRCLE_BUILD_URL:-${GITHUB_BUILD_URL:-${DESCRIPTION}}}"

CLEAN_BRANCH_NAME="${BRANCH_NAME//\//_}"
CLEAN_DESCRIPTION="${DESCRIPTION/https*:\/\//}"

GIT_COMMIT="$(git rev-parse --verify HEAD)"

VERSION="${EB_APP_NAME}-${CLEAN_BRANCH_NAME}-${BUILD_NUMBER}-${GIT_COMMIT}"

PACKAGE="${VERSION}.zip"

cp config/database.yml.beanstalk config/database.yml

.elasticbeanstalk/package.py "${PACKAGE}"

aws s3 cp --no-progress ".elasticbeanstalk/app_versions/${PACKAGE}" "s3://${S3_BUCKET_NAME}/${EB_APP_NAME}/"

aws elasticbeanstalk create-application-version \
    --debug \
    --application-name "${EB_APP_NAME}" \
    --version-label "${VERSION}" \
    --source-bundle "S3Bucket=${S3_BUCKET_NAME},S3Key=${EB_APP_NAME}/${PACKAGE}" \
    --description "${CLEAN_DESCRIPTION}" \
    --no-process

#!/usr/bin/env bash

set -euxo pipefail

EB_APP_NAME="${1}"
S3_BUCKET_NAME="${2}"

BRANCH_NAME="${CIRCLE_BRANCH:-${BRANCH_NAME}}"
BUILD_NUMBER="${CIRCLE_BUILD_NUM:-${BUILD_NUMBER}}"
DESCRIPTION="${CIRCLE_BUILD_URL:-${DESCRIPTION}}"

CONTAINER_SHA="$(git rev-parse --short=7 HEAD)"
BUNDLE="sha-${CONTAINER_SHA}.zip"
VERSION="${EB_APP_NAME}-${CLEAN_BRANCH_NAME}-${BUILD_NUMBER}-${GIT_COMMIT}"

GRAFANA_IMAGE="docker.pkg.github.com/safecast/reporting2/grafana:sha-${CONTAINER_SHA}"

jq --arg image "${GRAFANA_IMAGE}" \
  '.containerDefinitions | .[] | select(.name == "grafana").image = $image' \
  Dockerrun.aws.json > Dockerrun.aws.json.updated
mv Dockerrun.aws.json.updated Dockerrun.aws.json

mkdir -p .elasticbeanstalk/app_versions

zip -r ".elasticbeanstalk/app_versions/${BUNDLE}" . \
  -x \
    '.gitignore' \
    '.git/*' \
    '.idea/*' \
    '.github/*' \
    '.elasticbeanstalk/*' \
    '.envrc'

aws s3 cp --no-progress ".elasticbeanstalk/app_versions/${BUNDLE}" "s3://${S3_BUCKET_NAME}/${EB_APP_NAME}/"

aws elasticbeanstalk create-application-version \
    --application-name "${EB_APP_NAME}" \
    --version-label "${VERSION}" \
    --source-bundle "S3Bucket=${S3_BUCKET_NAME},S3Key=${EB_APP_NAME}/${PACKAGE}" \
    --description "${CLEAN_DESCRIPTION}" \
    --no-process
